# Generated by Django 3.1.2 on 2020-10-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer3d',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='printer3d',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
