# Generated by Django 3.1.2 on 2020-10-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20201017_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('object3d', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='matching.object3d')),
                ('object_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='object_owner_user_id', to=settings.AUTH_USER_MODEL)),
                ('printer3d', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='matching.printer3d')),
                ('printer_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='printer_owner_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(verbose_name='text')),
                ('receiver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_user_id', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sender_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
