# Generated by Django 3.1.2 on 2020-10-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_dm_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='matching.request'),
        ),
    ]
