# Generated by Django 3.1.2 on 2020-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20201017_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object3d',
            name='stl',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
