# Generated by Django 3.1.1 on 2020-10-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object3d',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='object3d',
            name='stl',
            field=models.BinaryField(default=b'\x01'),
        ),
        migrations.AlterField(
            model_name='object3d',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='matching.user'),
        ),
        migrations.CreateModel(
            name='Printer3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=256)),
                ('max_width', models.FloatField(default=0.0)),
                ('max_height', models.FloatField(default=0.0)),
                ('max_depth', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='matching.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=256)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='matching.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filament3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=256)),
                ('genre', models.CharField(default='', max_length=256)),
                ('thin', models.FloatField(default=0.5)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='matching.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
